services:
  api:
    build:
      context: .
    container_name: kaya-backend
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    restart: "no"
    command: "fastapi dev app/main.py --port 8000 --host 0.0.0.0 --reload"
    volumes:
      - ./app:/code/app
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: postgres
    image: postgres
    environment:
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
      POSTGRES_DB: postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db:
