"""add tables

Revision ID: f9e88e3efe1b
Revises: 
Create Date: 2024-12-10 22:52:30.373980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9e88e3efe1b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ad_group',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ad_group_stat',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ad_group_id', sa.BigInteger(), nullable=False),
    sa.Column('device', sa.String(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('conversions', sa.Numeric(), nullable=False),
    sa.Column('cost', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['ad_group_id'], ['ad_group.id'], ),
    sa.PrimaryKeyConstraint('date', 'ad_group_id', 'device')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ad_group_stat')
    op.drop_table('ad_group')
    op.drop_table('campaign')
    # ### end Alembic commands ###
